import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { createClient } from 'contentful'


export default function Home({mainSection}) {

  const { 
    title,
    backgroundImage: {
      fields: {
        file: {
          url,
          details: {
            image: {
              height,
              width
            }
          }
        }
      }
    }
  } = mainSection[0].fields

  return (
    <div className={styles.container}>
      <Head>
        <title>VencoachSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}

export async function getStaticProps() {

  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken:process.env.CONTENTFUL_DELIVERY_ACCESS_TOKEN,
  })

  const resp = await client.getEntries({content_type: 'mainSection' })

  return {
    props: {
      mainSection: resp.items
    }
  }

}