import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { createClient } from 'contentful'


export default function Home({mainSection}) {

  const { 
    title,
    backgroundImage: {
      fields: {
        file: {
          url,
          details: {
            image: {
              height,
              width
            }
          }
        }
      }
    }
  } = mainSection[0].fields

  return (
    <div className={styles.container}>
      <Head>
        <title>VencoachSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {title}
        </h1>

        <div>
          <Image 
            src={`https:${url}`}
            width={width}
            height={height}
            alt='city'
          />
        </div>

        <p className={styles.description}>
          Development in process..
        </p>

        
      </main>

      <footer className={styles.footer}>
        copyright &copy; VENCOACH 2022
      </footer>
    </div>
  )
}

export async function getStaticProps() {

  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken:process.env.CONTENTFUL_DELIVERY_ACCESS_TOKEN,
  })

  const resp = await client.getEntries({content_type: 'mainSection' })

  return {
    props: {
      mainSection: resp.items
    }
  }

}