import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>VencoachSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          VENCOACH SITE
        </h1>

        <p className={styles.description}>
          Development in process..
        </p>

        
      </main>

      <footer className={styles.footer}>
        copyright &copy; VENCOACH 2022
      </footer>
    </div>
  )
}
